"""player playing status

Revision ID: 13974b232218
Revises: bf534e7c1f3e
Create Date: 2023-02-16 19:53:06.202337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13974b232218'
down_revision = 'bf534e7c1f3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_members', sa.Column('is_playing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_members', 'is_playing')
    # ### end Alembic commands ###
