"""busy room status

Revision ID: 82f48c6b0bb1
Revises: 13974b232218
Create Date: 2023-02-16 20:01:27.477694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f48c6b0bb1'
down_revision = '13974b232218'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('busy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'busy')
    # ### end Alembic commands ###
