"""active status

Revision ID: bf534e7c1f3e
Revises: 4baec27f0b8b
Create Date: 2023-02-14 21:03:49.876301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf534e7c1f3e'
down_revision = '4baec27f0b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('active_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'active_status')
    # ### end Alembic commands ###
